### ISSUE TITLE
Missing GCC5 support

### ISSUE THREAD

**Issue by telphan** [hardkernel/u-boot#20]
Trying to compile this u-boot on v2011.03 under GCC 5.2 will yield the following compile error:

include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc5.h: No such file or directory compilation terminated.

Copying the file from the linux tree will yield other compile issues.

**Comment by fboudra** [comment]
it can be fixed with https://github.com/hardkernel/u-boot/pull/24

**Comment by bkrepo** [comment]
Merged.
