### ISSUE TITLE
Uboot's toolchain is arm-linux-gnueabihf, But Kernel's toolchain is arm-eabi-

### ISSUE THREAD

**Issue by trickyMan** [hardkernel/u-boot#33]
Uboot's toolchain is arm-linux-gnueabihf, But Kernel's toolchain is arm-eabi-

Can I use ONLY arm-linux-gnueabihf- or arm-eabi- to build the both of Uboot & Kernel?

**Comment by bkrepo** [comment]
Pre-built bl301.bin is added for built fail issue.
