### ISSUE TITLE
ODROID-C2: BL1 license text needed

### ISSUE THREAD

**Issue by afaerber** [hardkernel/u-boot#39]
`sd_fuse/bl1.bin.hardkernel` is documented [in the Wiki](http://odroid.com/dokuwiki/doku.php?id=en:c2_building_u-boot#installation) to be "provided as prebuilt binary only".

Since this file is necessary for booting, can you please clarify the license of this file?
In particular I am in need of a clear statement of whether your binary file is redistributable (for packaging and creation of third-party Linux images).

Having some `LICENSE.bl1` file next to `bl1.bin.hardkernel` would be ideal.

**Comment by bkrepo** [comment]
The "bl1.bin.hardkernel" file was generated by Amlogic for Hardkernel ODROID-C2 platform.
It works with ODROID-C2 board only and everybody can redistribute it.
There is no restriction.
