### ISSUE TITLE
netbook for xu?

### ISSUE THREAD

**Issue by ericvh** [hardkernel/u-boot#4]
u-boot does seem to detect ethernet when it comes up.  It would be a nice addition to be able to netboot the odroid-xu.  Thanks.

**Comment by rzk** [comment]
On all recent odroid boards networking is connected this way: Exynos SoC USB HSIC -> SMSC USB HSIC to USB2.0 converter -> SMSC USB-Ethernet with hub.
So, to have network boot, you need to setup all of these, and current u-boot can only hande internal exynos usb-host, not the HSIC. Luckily, some of the work is already done, there is a driver for SMSC USB-Ethernet http://git.denx.de/?p=u-boot.git;a=blob;f=drivers/usb/eth/smsc95xx.c, but I have no idea about everything else. If you can get the NDA'd user manuals for Exynos SoCs and write the support - go on.

Also, ODROID has public forums, where you should post this, probably in this section http://forum.odroid.com/viewforum.php?f=55

Best Regards,
Dmitriy Beykun

**Comment by mdrjr** [comment]
We have no plan right now to add this support to u-boot.

Thank you for your idea. We'll consider it.

Best Regards,
Mauro
