### ISSUE TITLE
Pull requests lost by forced commit

### ISSUE THREAD

**Issue by xypron** [hardkernel/u-boot#43]
@codewalkerster
It seems you used a forced commit.
You have lost the correction from pull requests #41 and #42.
Could you, please, merge #41 and #42 again.

You can restore the missing patches with

    git checkout 255256b4e8603b2523b12e97d9efd0f625e19823
    git rebase origin/odroidc2-v2015.01
    git push

Best regards

Heinrich Schuchardt

**Comment by tobetter** [comment]
@xypron Thank you for kind notice, the branch has been pushed with your commits.
