### ISSUE TITLE
odroid N2 after firmware upgrade to Kernel 5.XX black boot screen 

### ISSUE THREAD

**Issue by linuxonlinehelp** [hardkernel/u-boot#59]
odroid N2 after firmwareupgrade to Kernel 5.XX black boot screen
i did:
- fresh setup to micro sd debian stretch minimal 4.9
- upgrade the OS by apt to buster and apt-get dist-upgrade, Kernel 4.9 runs+reboot ok
- armbian-config firmware upgrade, reboot, no boot, black screen of death Kernel 5.0..

Howto install 2 versions of Kernel to boot? and switch?
or does uboot only handle one kernel at /boot?

**Comment by mdrjr** [comment]
That's not our image, its a 3rd party image and you should ask armbian for help.

**Comment by tobetter** [comment]
@linuxonlinehelp You could consider using my image which not an official image from Hardkernel. But the image can have two different kernels and can switch. Please keep posting your doubts in the thread if you have any.
https://forum.odroid.com/viewtopic.php?f=176&t=33993&hilit=mainline&start=100#p268080
