### ISSUE TITLE
fip_create, aml_encrypt_g12a for aarch64

### ISSUE THREAD

**Issue by sndwvs** [hardkernel/u-boot#62]
when trying to build a u-boot for odroid-c4 on **aarch64** architecture, compiled utilities **fip/fip_create** and
**fip/g12a/aml_encrypt_g12a** are compiled for the **x86_64** architecture, you can get the utility data for aarch64 or specify the sources for the build.

**Comment by matwey** [comment]
There is (unofficial) open-source replacement for aml_encrypt_g12a: https://github.com/angerman/meson64-tools
You also may use qemu binfmt to run x86_64 binary at aarch64 system.

**Comment by arapov** [comment]
@matwey, have you had a chance to actually try it? afaik, **aml_encrypt_g12a** is different from  **aml_encrypt_g12b**, which is available in the repo you pointed to.

**Comment by matwey** [comment]
Yes, I am able to create working boot-loader for Odroid-C4, which is `g12a`.

**Comment by arapov** [comment]
@matwey it works, indeed! I had to look inside long before... thank you!
