### ISSUE TITLE
Odroid C4 and N2 does not boot using kernel 5.10-rcX

### ISSUE THREAD

**Issue by Strit** [hardkernel/u-boot#63]
At Manjaro ARM, we like to be looking forward and as such we try the RC upstream kernels when we can.

The Odroid C4 and Odroid N2 has booted just fine with upstream kernels up to 5.9, if you change the TEXT_OFFSET, set in arm/arm64/Makefile of the kernel, differently.
But kernel 5.10 has now removed TEXT_OFFSET support entirely.

This means, that the 5.10 kernel cannot boot, if we use this old (2015) u-boot from Hardkernel.
And it's not possible to build mainline uboot on aarch64 that works, since it requires x86_64 binaries (see https://github.com/hardkernel/u-boot/issues/62).

Attached is a boot log from Odroid C4, with Uboot 2015.1 from Hardkernel and kernel 5.10-rc2 from kernel.org.
[5.10-uboot.log](https://github.com/hardkernel/u-boot/files/5493311/5.10-uboot.log)

**Comment by bjharper** [comment]
Some possible workarounds requiring some more investigation include

1) Wrapping the kernel image in a uImage format (using mkimage) specifically defining the entry points that the kernel should boot into
2) mainline uboot (or bsp uboot) can be built on arm64 by using qemu x64 emulation

**Comment by Strit** [comment]
Issue resolved.

Had to change
setenv initrd_loadaddr "0x3080000"
in boot.ini to
setenv initrd_loadaddr "0x4080000"

And now it works again with both 5.9.y and 5.10 RC's.

**Comment by cattyhouse** [comment]
Hi Strit, thanks for the tip. I have a similar A53 box and it is also the old uboot 2015. I have these events, it boots 5.9 fine ( with text_offset mod in Makefile)
````
setenv env_addr 0x10400000
setenv kernel_addr 0x11000000
setenv initrd_addr 0x13000000
````

How should i make the change to boot 5.10? Thanks.

**Comment by cattyhouse** [comment]
@Strit any help would be appreciated

**Comment by Strit** [comment]
Try changing the `setenv initrd_addr` to `0x4080000`.

That's what worked for me.

**Comment by cattyhouse** [comment]
@strit how did you get that value?

**Comment by Strit** [comment]
From an Ubuntu image I think...
