### ISSUE TITLE
Odroid-C4 does not boot

### ISSUE THREAD

**Issue by SebiTimeWaster** [hardkernel/u-boot#70]
using https://github.com/hardkernel/u-boot/releases/tag/travis/odroidn2-171 (or https://github.com/hardkernel/u-boot/releases/tag/travis%2Fodroidc4-153 or 3 other older versions):

i cannot get my Odroid-C4 to boot (or at least show something), it just has a black screen, the mouse lights flash for half a second and nothing is happening. board light is permanent blue.

i used the shell script that is included.
another test with an Ubuntu image succeeded to boot.

**Comment by SebiTimeWaster** [comment]
i also tried the bin from this zip, same result: https://forum.odroid.com/viewtopic.php?f=206&t=39608

**Comment by SebiTimeWaster** [comment]
i dont want to be impatient, but i really would like to use my new hardware... :(

**Comment by SebiTimeWaster** [comment]
i tried to follow these instructions but it also did not work: https://u-boot.readthedocs.io/en/latest/board/amlogic/odroid-c4.html

also they where confusing at best...

**Comment by SebiTimeWaster** [comment]
hellooooo....

**Comment by tobetter** [comment]
Sorry, you would be better to post the issues to ODROID forum.
I am seeing three different problems from you posts, have you tried to boot with official Ubuntu/Android image?

**Comment by SebiTimeWaster** [comment]
![image](https://user-images.githubusercontent.com/3726309/106941698-776bc580-6723-11eb-9d0b-dd095b91f667.png)
